spring:
application:
name: mdm-formacion-alta
datasource:
driverClassName: oracle.jdbc.OracleDriver
password: ${BBDD_PASSWORD}
url: ${BBDD_URL}
username: ${BBDD_USERNAME}
jpa:
show-sql: true
database-platform: org.hibernate.dialect.OracleDialect
hibernate:
  use-new-generator-mappings=false
rabbitmq:
virtual-host: ${VIRTUAL_HOST_RABBIT}
host: ${RABBIT_HOST}
port: ${PORT_RABBIT}
addresses: ${URL_RABBIT}:${PORT_RABBIT}
username: ${USERNAME_RABBIT}
password: ${PASSWORD_RABBIT}
requested-heartbeat: ${RABBIT_HEARTBEAT:60}
cache:
channel:
size: ${RABBIT_CHANNEL_SIZE:16}
mdm:
protocol: soap
orsId: ${ORS_ID}
url: ${MDM_URL}
username: ${MDM_USERNAME}
password: ${MDM_PASSWORD}
feign:
hystrix:
enabled: true

